# Generated by Django 5.2.1 on 2025-05-11 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                ("is_featured", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
                ("email", models.EmailField(blank=True, max_length=64, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("about", models.TextField(blank=True, max_length=1024, null=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("head_line", models.CharField(blank=True, max_length=255, null=True)),
                ("is_vendor", models.BooleanField(blank=True, null=True)),
                ("is_adult", models.BooleanField(blank=True, null=True)),
                ("email_verified", models.BooleanField(blank=True, null=True)),
                ("online", models.BooleanField(blank=True, null=True)),
                ("completed_registration", models.BooleanField(blank=True, null=True)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("time_zone", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "availability_type",
                    models.CharField(
                        blank=True,
                        choices=[("d", "One-day or Daily"), ("w", "Weekly")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "repeat_on",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated weekdays (1=Mon ... 7=Sun)",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("profile_photo", "Profile Photo"),
                            ("company_logo", "Company Logo"),
                            ("conversation_video", "Video Conversation"),
                            ("certification_photo", "License/Certification"),
                            ("education_photo", "Education"),
                            (
                                "letter_of_recommendation_photo",
                                "Letter Of Recommendation",
                            ),
                            ("career_photo", "Career Photo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_categories",
                        to="profiles.category",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_categories",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "profile_category",
                "indexes": [
                    models.Index(
                        fields=["category"], name="fk_user_category_category1_idx"
                    ),
                    models.Index(
                        fields=["profile"], name="fk_user_category_profile1_idx"
                    ),
                ],
                "unique_together": {("category", "profile")},
            },
        ),
    ]
