# Generated by Django 5.2.1 on 2025-05-12 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('O', 'Other'), ('U', 'Prefer not to say')], default='U', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profilecategory',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Less than 1 year of experience'), (1, '1 year of experience'), (2, '2 years of experience'), (3, '3 years of experience'), (4, '4 years of experience'), (5, '5 years of experience'), (6, '6 years of experience'), (7, '7 years of experience'), (8, '8 years of experience'), (9, '9 years of experience'), (10, '10 years of experience'), (11, '11 years of experience'), (12, '12 years of experience'), (13, '13 years of experience'), (14, '14 years of experience'), (15, '15 years of experience'), (16, '16 years of experience'), (17, '17 years of experience'), (18, '18 years of experience'), (19, '19 years of experience'), (20, '20 years of experience'), (99, 'More than 20 years of experience')], default=0),
        ),
        migrations.CreateModel(
            name='ProfileLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=16)),
                ('is_native', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.language')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile', 'language')},
            },
        ),
    ]
